include: ".ci-templates.yml"

stages:
  - test
  - build-image
  - generate-client
  - publish-client
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .pip-cache/

test:
  stage: test
  extends:
    - .environment-django-ci
  script:
    # # Run pytest with generation both HTML and Cobertura XML coverage reports, and JUnit XML test report
    # if no tests found, convert exit code 5 to 0
    - pytest --cov=. --cov-report html --cov-report xml:coverage.xml --cov-report term --junitxml=report.xml || [ $? -eq 5 ]
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: report.xml
    paths:
      - htmlcov/
      - coverage.xml
      - report.xml

# build and push docker image to registry
build-push-api-image:
  stage: build-image
  extends:
    - .can-build-kaniko
    - .build-kaniko
  variables:
    IMAGE_NAME: boilerplate/api
    IMAGE_TAG: $CI_COMMIT_SHORT_SHA
    DOCKERFILE_PATH: "Dockerfile"
    DOCKER_BUILD_ARGS: ""

build-push-webapi-image:
  stage: build-image
  extends:
    - .can-build-kaniko
    - .build-kaniko
  variables:
    IMAGE_NAME: boilerplate/webapi
    IMAGE_TAG: $CI_COMMIT_SHORT_SHA
    LATEST_TAG: latest
    DOCKERFILE_PATH: "nginx/Dockerfile"
    DOCKER_BUILD_ARGS: ""
  script:
    - /kaniko/executor --context ./nginx --dockerfile $DOCKERFILE_PATH --destination $REGISTRY_URL/$IMAGE_NAME:$IMAGE_TAG $DOCKER_BUILD_ARGS
    - /kaniko/executor --context ./nginx --dockerfile $DOCKERFILE_PATH --destination $REGISTRY_URL/$IMAGE_NAME:$LATEST_TAG $DOCKER_BUILD_ARGS
  rules:
    - changes:
        - nginx/**/*
      when: always

deploy-testing:
  stage: deploy
  variables:
    ENVIRONMENT: testing
    ENVIRONMENT_URL: https://api.testing.boilerplate.appftth.fr
    ENV_FILE: $ENV_TESTING
    SSH_HOST: $SSH_TESTING_HOST
    SSH_PORT: $SSH_TESTING_PORT
    API_IMAGE_NAME: boilerplate/api
    API_IMAGE_TAG: $CI_COMMIT_SHORT_SHA
    WEB_API_IMAGE_NAME: boilerplate/webapi
    WEB_API_IMAGE_TAG: latest
  extends:
    - .on-main
    - .deploy-environment

deploy-staging:
  stage: deploy
  variables:
    ENVIRONMENT: staging
    ENVIRONMENT_URL: https://api.staging.boilerplate.appftth.fr
    ENV_FILE: $ENV_STAGING
    SSH_HOST: $SSH_STAGING_HOST
    SSH_PORT: $SSH_STAGING_PORT
    API_IMAGE_NAME: boilerplate/api
    API_IMAGE_TAG: $CI_COMMIT_SHORT_SHA
    WEB_API_IMAGE_NAME: boilerplate/webapi
    WEB_API_IMAGE_TAG: latest
  extends:
    - .on-release
    - .deploy-environment

deploy-production:
  stage: deploy
  variables:
    ENVIRONMENT: production
    ENVIRONMENT_URL: https://api.boilerplate.appftth.fr
    ENV_FILE: $ENV_PROD
    SSH_HOST: $SSH_PROD_HOST
    SSH_PORT: $SSH_PROD_PORT
    API_IMAGE_NAME: boilerplate/api
    API_IMAGE_TAG: $CI_COMMIT_SHORT_SHA
    WEB_API_IMAGE_NAME: boilerplate/webapi
    WEB_API_IMAGE_TAG: latest
  extends:
    - .on-release-manual
    - .deploy-environment
