version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env.dev
    ports:
      - 8000:8000
    volumes:
      - .:/home/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      - rabbitmq
      - redis
      - smtp

  celery:
    build: .
    env_file:
      - ./.env.dev
    volumes:
      - .:/home/app
    command: celery -A config worker --loglevel=info
    depends_on:
      - db
      - rabbitmq
      - redis
      - smtp

  celery-beat:
    build: .
    env_file:
      - ./.env.dev
    volumes:
      - .:/home/app
    command: celery -A config beat --loglevel=info
    depends_on:
      - db
      - rabbitmq
      - redis
      - smtp

  smtp:
    image: maildev/maildev
    ports:
      - 1025:1025
      - 1080:1080

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nao
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  postgres_data:
