version: "3"
services:
  api:
    image: $REGISTRY_URL/$API_IMAGE_NAME:$API_IMAGE_TAG
    env_file:
      - ./.env
    ports:
      - 8001:8001
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8001 --workers 4 --timeout 120
    networks:
      - boilerplate_network
    volumes:
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/mediafiles

  web_api:
    image: $REGISTRY_URL/$WEB_API_IMAGE_NAME:$WEB_API_IMAGE_TAG
    restart: always
    ports:
      - 8000:8000
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    depends_on:
      - api
    networks:
      - boilerplate_network

volumes:
  static_volume:
  media_volume:

networks:
  boilerplate_network:
    driver: bridge
    name: boilerplate_network
