version: "3"
services:
  api:
    image: $REGISTRY_URL/$API_IMAGE_NAME:${API_IMAGE_TAG:-latest}
    env_file:
      - ./.env
    ports:
      - 8001:8001
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8001 --workers 4 --timeout 120
    depends_on:
      - db
    networks:
      - boilerplate_network
    volumes:
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/mediafiles

  web_api:
    image: $REGISTRY_URL/$WEB_API_IMAGE_NAME:${WEB_API_IMAGE_TAG:-latest}
    restart: always
    ports:
      - 8000:8000
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    depends_on:
      - api
    networks:
      - boilerplate_network

  db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=boilerplate
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - boilerplate_network

  adminer:
    image: adminer
    ports:
      - 9000:8080
    networks:
      - boilerplate_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  boilerplate_network:
    driver: bridge
    name: boilerplate_network
