version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - ./.env.staging
    ports:
      - 8001:8001
    command: daphne config.asgi:application --bind 0.0.0.0 --port 8001
    networks:
      - boilerplate_staging_network
    volumes:
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/mediafiles

  web_api:
    build: ./nginx
    restart: always
    ports:
      - 8000:8000
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    depends_on:
      - api
    networks:
      - boilerplate_staging_network

volumes:
  static_volume:
  media_volume:

networks:
  boilerplate_staging_network:
    driver: bridge
    name: boilerplate_staging_network
