version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - ./.env.testing
    ports:
      - 8001:8001
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8001 --workers 4 --timeout 120
    depends_on:
      - db
    networks:
      - boilerplate_testing_network
    volumes:
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/mediafiles

  web_api:
    build: ./nginx
    restart: always
    ports:
      - 8000:8000
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    depends_on:
      - api
    networks:
      - boilerplate_testing_network

  celery:
    build: .
    env_file:
      - ./.env.testing
    volumes:
      - .:/home/app
    command: celery -A config worker --loglevel=info
    depends_on:
      - db
      - rabbitmq
      - redis
    networks:
      - boilerplate_testing_network

  celery-beat:
    build: .
    env_file:
      - ./.env.testing
    volumes:
      - .:/home/app
    command: celery -A config beat --loglevel=info
    depends_on:
      - db
      - rabbitmq
      - redis
    networks:
      - boilerplate_testing_network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - boilerplate_testing_network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - boilerplate_testing_network

  db:
    image: postgres:15
    ports:
      - 5432:5432
    env_file:
      - ./.env.db.testing
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - boilerplate_testing_network

  adminer:
    image: adminer
    ports:
      - 9000:8080
    networks:
      - boilerplate_testing_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  boilerplate_testing_network:
    driver: bridge
    name: boilerplate_testing_network
