version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env.dev
    ports:
      - 8000:8000
    volumes:
      - .:/home/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    networks:
      - boilerplate_dev_network

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=boilerplate
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - boilerplate_dev_network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - boilerplate_dev_network

volumes:
  postgres_data:

networks:
  boilerplate_dev_network:
    driver: bridge
    name: boilerplate_dev_network
