# Generated by Django 4.2.13 on 2024-07-01 08:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TestModels",
        ),
    ]
