# Generated by Django 4.2.13 on 2024-06-27 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0008_historicaluser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="unite",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="authentication.unite",
            ),
        ),
    ]
